version: '3'
services:

  stubby4j:
    image: sandokandias/stubby4j-docker
    ports:
      - 8883:8883
    environment:
      STUBBY_PORT: 8883
    volumes:
      - ./assets/stubby4j/integrations.yaml:/usr/local/stubby.yml

  cli:
    build:
      context: ./cli
      dockerfile: build/cli/Dockerfile
    depends_on:
      - stubby4j
    command: sh -c 'while sleep 3600; do :; done'
    environment:
      - DEFAULT_SERVER_URL=https://server:8080
      - DEFAULT_SERVER_MOCK_URL=http://stubby4j:8883

  server:
    build:
      context: ./server
      dockerfile: build/server/Dockerfile
    command: sh -c 'while sleep 3600; do :; done'
    ports:
      - 8080:8080
    environment:
      - LOGS_DIR=/app/server/logs
      - TLS_CERT_FILE_PATH=/app/server/cert/server.crt
      - TLS_KEY_FILE_PATH=/app/server/cert/server.key
      - JWT_CERT_FILE_PATH=/app/server/cert/jwt.crt
