linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - goimports
    - golint
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - unconvert
    - varcheck

output:
  uniq-by-line: false
