version: '3'
services:

  stubby4j:
    image: sandokandias/stubby4j-docker
    ports:
      - 8883:8883
    environment:
      STUBBY_PORT: 8883
    volumes:
      - ./assets/stubby4j/integrations.yml:/usr/local/stubby.yml

  cli:
    build:
      context: .
      dockerfile: ./build/cli/Dockerfile
    depends_on:
      - stubby4j
    command: sh -c 'while sleep 3600; do :; done'
